### ISSUE TITLE
UI option never hidden, always starts out unchecked

### ISSUE THREAD

**Issue by Black-Platypus** [hako-mikan/sd-webui-negpip#53]
The accordion UI item is never hidden, like the setting "Hide in Txt2Img/Img2Img tab" suggests.
This leads to the menu spawning in unchecked, which has lead to much confusion 😅
I don't know how the UI/Settings system works, but it looks like the settings value for "negpip_hide" is read into `opt_hideui`, without that variable ever being used. 
https://github.com/hako-mikan/sd-webui-negpip/blob/db6e47d94c7255b6f48561ed6d3aa2d3524ef159/scripts/negpip.py#L44
The settings value is queried again only in `process_batch`.
Also, I can't get the "Toggle startup Active" button to work. I assume the checkbox should start out being checked?

**Comment by hako-mikan** [comment]
Thanks!
It looks like I missed that the visible setting was left out when I approved pull request #45.
Fixed it.

**Comment by Black-Platypus** [comment]
The hiding option works now.
However, it always starts off disabled (including when it is hidden); that problem still persists.
Using a fresh install with only NegPiP installed (except for the built-in extensions)

My `ui-config.json` contains:
```
    "customscript/negpip.py/txt2img/NegPiP/visible": true,
    "customscript/negpip.py/txt2img/NegPiP/value": false,
    "txt2img/Toggle startup with Active(Now:None)/visible": true,
    "customscript/negpip.py/img2img/NegPiP/visible": true,
    "customscript/negpip.py/img2img/NegPiP/value": null,
    "img2img/Toggle startup with Active(Now:None)/visible": true,
    "customscript/negpip.py/txt2img/Active/value": true,
    "txt2img/Toggle startup with Active(Now:False)/visible": true,
    "txt2img/Toggle startup with Active(Now:True)/visible": true
```
`customscript/negpip.py/txt2img/NegPiP/value` always seems to stay `false`

Does it matter that the caption text is different between https://github.com/hako-mikan/sd-webui-negpip/blob/8d066a3ee28111d9ed75a65a9a7d021e9cb921c8/scripts/negpip.py#L79 and https://github.com/hako-mikan/sd-webui-negpip/blob/8d066a3ee28111d9ed75a65a9a7d021e9cb921c8/scripts/negpip.py#L91 ?
I.e. "Toggle startup [WITH ]Active"?
Does that somehow affect things? I wouldn't think so, but I want to make sure 😅

https://github.com/user-attachments/assets/e7171b9f-3d2d-4dbb-8427-8d98413261f2

**Comment by hako-mikan** [comment]
If you hide it, you can turn the functionality on or off in the "Active" setting under Settings. 
At this time, all settings on the generation tab will be disabled.

**Comment by Black-Platypus** [comment]
No, it always starts out deactivated for me, even when it is hidden and the "Active" setting it set.
Re-toggling the setting, reloading, nothing makes it work

**Comment by hako-mikan** [comment]
Judging from the situation, it seems that the contents of ui-config.json are either not being correctly rewritten or not being properly loaded.

**Comment by Black-Platypus** [comment]
Can you reproduce the issue, or do you have to work from my reports?
I.e. is this an issue on my end somehow? If so, that's strange: I tested the above on a fresh install, and without much customizing of settings 🤔
That does mean though that I do have two separate "installs" of SD-WebUI. Maybe there's one thing that the clean install shares with the setup I actively use? 🥴 
Nothing that I can see should cause an issue, of course, so I'm at a loss.

But if I'm the only person experiencing this, there must be something I have to do 😅
Let me know your thoughts, and thank you for your time and effort :)

**Comment by Black-Platypus** [comment]
I just tested the latest update ([b054b92](https://github.com/hako-mikan/sd-webui-negpip/commit/b054b92b0fec3b6a65c172aeae3adf45ce87949c)): Now it works for loading the UI for the first time! 🥳
However, changes only take effect when first starting the WebUI.
If you make changes while the server keeps running and refresh the page, it loads the state to what it was when the server was started.
(A restart is needed to see the effect)

If you could make it read its current setting on render (? refresh? I don't know which callbacks/events exist in the Automatic1111 WebUI 😅), that would complete the last bit of the issue.
Otherwise, a message indicating that you have to restart for the toggle/change to take effect would be nice on or after the button 😊

**Comment by DickJokez69** [comment]
I think I'm having this issue as well. So it's not isolated.
It's kind of a hard thing to really test, whether or not the negatives are working or not, so it could just be me. It definitely seems like introducing anything in the negatives seems to affect the output, though in the opposite desired effect. I.E. adding something as a negative weight seems to add that thing into the gen. So as a basic example if you prompted (blue eyes:-1.0), instead of changing the eyes from blue to another color, it enforces blue eyes.

That being said, again, I don't know if this is NegPip not working, or it's a case of "Don't think about pink elephants", where you're influencing generations by telling it NOT to do something.
In any case, something definitely feels off.

**Comment by hako-mikan** [comment]
Added " Needs Restart to Apply" to button.

**Comment by Black-Platypus** [comment]
> It's kind of a hard thing to really test, whether or not the negatives are working or not
Can you look at the console output?
For me, NegPip always logs something like "NegPiP enable, Positive: ???, Negative: ???" to the console.
For testing (or in general), you may want to up your logging verbosity in the environment arguments.
Though, [looking at the code](https://github.com/hako-mikan/sd-webui-negpip/blob/b15d63442af5c19707ca88cce7312891e518ad8f/scripts/negpip.py#L298), it looks like it's not using a logger/priority control. I don't know if there's something that intercepts `print` calls to do that, though (or if that's even possible. I'm not a Python person ^^)

**Comment by DickJokez69** [comment]
> > It's kind of a hard thing to really test, whether or not the negatives are working or not
> 
> Can you look at the console output? For me, NegPip always logs something like "NegPiP enable, Positive: ???, Negative: ???" to the console.
So I do get numbers next to those, but I'm not entirely sure how they're counted. It seems more like it's counting the amount of tokens in the positive/negative prompts that are weighted negatively. I honestly wouldn't mind an option that says which tokens/tags are being intercepted by negpip in the console.
But I guess _technically_ it _is_ working, but it always feels like adding any kind of negatively weighted tag to a positive prompt also makes it appear in the result.

**Comment by Black-Platypus** [comment]
Hmm, that shouldn't be 🤔
Is this the case even for simple test cases, like for example comparing an output for "fluffy pets" with a seed that shows cats and dogs vs "fluffy pets (dog:-1)" on the same seed?
SD is of course not great at adhering to all aspects/concepts of prompts closely as things get more complicated (or even simple concepts like relations and separating properties for two or more objects), but we should see less dog(-ness) in the output for this example.
If not, there probably is an issue somewhere indeed
